# ===============================
# KONEKSI KE SUPABASE POSTGRESQL
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# KONFIGURASI HIBERNATE / JPA
# ===============================
# DDL Auto 'update' akan otomatis membuat/memperbarui tabel di database sesuai file Model Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Opsional: Menampilkan log query SQL di terminal/console untuk memudahkan debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET}

app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000
app.cors.allowed-origins=*

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true