# ===============================
# KONEKSI KE SUPABASE POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.tydpfanyfpvxpxyhjcfv
spring.datasource.password=N7,BRz$4d/rz*Nb
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# KONFIGURASI HIBERNATE / JPA
# ===============================
# DDL Auto 'update' akan otomatis membuat/memperbarui tabel di database sesuai file Model Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Opsional: Menampilkan log query SQL di terminal/console untuk memudahkan debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true